language: ruby
rvm:
- 2.3.1
before_install: gem update --remote bundler
services:
  - postgresql
install:
- bundle install --retry=3
before_script:
  - psql -c 'create database coredump_chess_test;' -U postgres
script:
- bundle exec rspec
- bundle exec rubocop
deploy:
  provider: heroku
  api_key:
    secure: MTrwI42EX8tyGE9njbtQh5PFSsN+a2N3+f/NeE+wXkLCkJJ3BvNkUo1XBnqCIvTFKTj6E5LE3ezd20L+yiw74ccfwt4CY281+5WYGtQSM3nfXnIy2mVeiFg3OmvPxPCuyLIfxodidH96nx/Tl30ThoTKne0xeHhRZVVoRYUeBWgBNKivA7tiP53ElA+pS2Jy5U3JqHHm+Axh0eSzdOallhLQWqoS/4ib3Yi9ktOMrkU8tet0ADUWWX5RbotBCKo/nWHxSDiVbF298HS0tNwSfFuwH73BILCALy67DL9z6zIOdT6LJqLQ1kKf0KskzLJChngHmvRqaJ2VdJkiNmqaZ/X2m6v6/pQBGGiBx/8tN1PCh0Q0WM2tVSf9wTv59EcuKpBaxvm/RgkRvACZ9It66XQq/Jhvso4xPFFc68P9/ygzahbLFuqJyQfwKYCN1ELZXKuG9UjB4WCpyRKGT1LIWRojSbos1iuFPHwWxWAUHfCAQgJtX5hywuh3WXu7d/5caphVeUjV5CB4ZYKYmIRf+yzzZaYl+OntPKlvA6C56HxpW/DQE+3GhEMEnP81CWheJyGfZwWWUAuqGP9zy9LMzlWQ6dMEkDFk+ZH9hLqsKUiEdAJqPc4hhgCddH3kK1fCzuwSLsEVUCZL01k1BHdLXm5iPKKaz5DjIGWRWYMqpu8=
  app: coredump-chess
  on:
    repo: Coredump-FHP/chess
